name: Terraform apply

on:
  workflow_dispatch:     
  push:
    branches:
      - main
permissions:
  contents: write 

jobs:
  create:
    runs-on: ubuntu-latest
    
    env:
      working-directory: ./

       
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up mise
        uses: jdx/mise-action@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8.15.4

      - name: Install tools via mise
        run: mise install
        # shell: bash
        working-directory: ${{ env.working-directory }}  
  
      # - name: Setting up Terraform
      #   uses: hashicorp/setup-terraform@v2
        
      - name: Deploying the infrastructure
        working-directory: ${{ env.working-directory }}
        env:
          TF_VAR_newrelic_account_id: ${{ secrets.NEWRELIC_ACCOUNT_ID }}
          TF_VAR_newrelic_api_key: ${{ secrets.NEWRELIC_API_KEY }}
          TF_VAR_newrelic_region: US
        run: |
          terraform init
          terraform plan
          
          # terraform apply --auto-approve

  versioning:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8.15.9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Install Changesets CLI
        run: pnpm add -D @changesets/cli  

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
  

      - name: Run Changesets
        run: |
          pnpm exec changeset version
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "ci: version bump from changeset" || echo "No changes to commit"
          git push

        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}  

